### ISSUE TITLE
Add catagorical data notebook image to JH instance

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#30]

**Comment by tumido** [comment]
Add an image stream pulling image from https://github.com/aicoe-aiops/categorical-encoding/issues/2 into ODH deployed via O1.

**Comment by tumido** [comment]
- [x] The AI-CoE CI pipeline is set up to build the image into quay - https://github.com/aicoe-aiops/categorical-encoding/pull/3
- [x] Make the AICoE pipeline build "latest" tag, so our image can auto-update - https://github.com/aicoe-aiops/categorical-encoding/pull/11
- [x] Repo adjustments - define version variable, so bots can release - https://github.com/aicoe-aiops/categorical-encoding/pull/7
- [x] Repo adjustments - convert git submodules to a vcs pip dependency - https://github.com/aicoe-aiops/categorical-encoding/pull/8
- [x] Import image to JH instance:
  ```yaml
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: categorical-encoding-notebook
    labels:
      opendatahub.io/notebook-image: "true"
  spec:
    lookupPolicy:
      local: true
    tags:
      - from:
          kind: DockerImage
          name: quay.io/aicoe/categorical-encoding:latest
        name: latest
        importPolicy:
          scheduled: true
  ```

**Comment by martinpovolny** [comment]
I have tested the image in my JH instance.

With this fix: https://github.com/aicoe-aiops/categorical-encoding/pull/13 it works.

**Comment by tumido** [comment]
Resolved via https://github.com/operate-first/odh/pull/25
