### ISSUE TITLE
[EPIC] Categorical encoding JH notebooks deployment 

### ISSUE THREAD

**Issue by tumido** [operate-first/continuous-deployment#32]
This is a master task for categorical encoding JH images deployment within the Operate First CD. The aim is to have a fully transparent, open source, deterministic deployment of a selected usecase.

Steps:
- [ ] Set up a build pipeline for the public image https://github.com/aicoe-aiops/categorical-encoding
- [ ] Pushing JH images to public quay
- [ ] Deploying the build pipeline on operated-first cluster (?)
- [ ] Pulling it to operated-first JH
- [ ] Cloning data to operated-first cluster https://github.com/operate-first/continuous-deployment/issues/28
- [ ] Exposing the data to spark/Hue https://github.com/operate-first/continuous-deployment/issues/29
- [ ] Packaging automating Superset dashboard creation on the operated-first cluster https://github.com/operate-first/continuous-deployment/issues/30

**Comment by anishasthana** [comment]
` Pushing JH images to public quay` This is specifically only the categorical encoding JH images right? And would we be hosting this on aicoe-ci infrastructure initially?

Does ` Deploying the build pipeline on operated-first cluster (?)` mean we want to replicate the entire aicoe-ci infra in the operate-first cluster?

**Comment by tumido** [comment]
Ad 1. Yes, we need to offer publicly available images, so they can be pulled into any cluster outside RH firewall - therefore they need to be available on public quay (or anywhere else) instead of the internal registry.

Ad 2. Not sure. In the end we want to offer the full package - that also includes a way to build the images (for any repository) in public - any space the user chooses. This may not be relevant to the crawl phase, but it may be necessary in the end.

**Comment by anishasthana** [comment]
Shouldn't that be solved by having the pipeline files and stuff available on git? As well as information on _how_ to deploy it. I think everything aicoe-ci does is already on github.

**Comment by tumido** [comment]
In my view it should be a self contained package. If we know the information *how* to deploy it fully, why not offer it as a part of the operate first? Without compromises.

If JH images are the intended interface for adding new content to ODH, we should also provide an automated way to make it happen. It's not necessarily part of this task though. It's probably a big chunk of work on it's own. That's why I've put the question mark there. I think for now it's enough to be able to include a public image from any source and have it integrated in ODH automatically. But in the end, the user is expected and encouraged to create new content - new notebooks. And they can't be expected to deploy full AICoE-CI on their own manually. If we can make the experience smooth for them, it's just lowering the entry barrier.

However that's just my view on this, so if there's any reason why not to do it, let's bring it up. I'm not aware of any, except time and manpower at this exact moment, which is just matter of priorities and scoping.

**Comment by anishasthana** [comment]
That's fair, I was thinking of it from a time and manpower perspective :-)
